apiVersion: v1
kind: Pod
metadata:
  labels:
    app: go-ceph
  name: go-ceph
  namespace: rook-ceph
spec:
  containers:
  - args:
    - "86400"
    command:
    - sleep 
    env:
    - name: ROOK_CEPH_USERNAME
      valueFrom:
        secretKeyRef:
          key: ceph-username
          name: rook-ceph-mon
    - name: ROOK_CEPH_SECRET
      valueFrom:
        secretKeyRef:
          key: ceph-secret
          name: rook-ceph-mon
    image: bougou/goceph
    imagePullPolicy: IfNotPresent
    name: go-ceph
    resources: {}
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/ceph
      name: ceph-config
    - mountPath: /etc/rook
      name: mon-endpoint-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-htfx4
      readOnly: true
  dnsPolicy: ClusterFirstWithHostNet
  enableServiceLinks: true
  nodeName: a100-2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 5
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: data
        path: mon-endpoints
      name: rook-ceph-mon-endpoints
    name: mon-endpoint-volume
  - emptyDir: {}
    name: ceph-config
  - name: kube-api-access-htfx4
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
